Repository foundation-model-stack/fms-hf-tuning, pull requests merged in 2024-09, with the labels that each got.

#343 fix: Addition of default pad token in tokenizer when EOS and PAD token are equal
  tuning/sft_trainer.py
Labels: fix

#280 feat: Add DataClass Arguments to Activate Padding-Free and MultiPack Plugin and FastKernels
  README.md
  tests/acceleration/spying_utils.py
  tests/acceleration/test_acceleration_dataclasses.py
  tests/acceleration/test_acceleration_framework.py
  tests/test_sft_trainer.py
  tuning/config/acceleration_configs/__init__.py
  tuning/config/acceleration_configs/acceleration_framework_config.py
  tuning/config/acceleration_configs/attention_and_distributed_packing.py
  tuning/config/acceleration_configs/fused_ops_and_kernels.py
  tuning/sft_trainer.py
Labels: feat

#349 fix: cap transformers at v4.44
  pyproject.toml
Labels: fix

#338 fix: utilities to post process checkpoint for LoRA
  README.md
  build/utils.py
  scripts/post_process_adapters_vLLM.py
  tests/artifacts/tuned_llama_with_added_tokens/adapter_config.json
  tests/artifacts/tuned_llama_with_added_tokens/adapter_model.safetensors
  tests/artifacts/tuned_llama_with_added_tokens/added_tokens.json
  tests/artifacts/tuned_llama_with_added_tokens/special_tokens_map.json
  tests/artifacts/tuned_llama_with_added_tokens/tokenizer.json
  tests/artifacts/tuned_llama_with_added_tokens/tokenizer_config.json
  tests/build/test_launch_script.py
  tests/test_sft_trainer.py
  tests/utils/test_merge_model_utils.py
  tests/utils/test_tokenizer_data_utils.py
  tuning/data/tokenizer_data_utils.py
  tuning/sft_trainer.py
  tuning/utils/merge_model_utils.py
Labels: fix

#351 feat: Add post processing logic to accelerate launch
  build/README.md
  build/accelerate_launch.py
  tests/build/test_launch_script.py
Labels: feat

#350 build: install additional fms-acceleration plugins
  README.md
  build/Dockerfile
  tuning/config/acceleration_configs/acceleration_framework_config.py
Labels: build

#352 fix: unable to find output_dir in multi-GPU during resume_from_checkpoint check
  build/accelerate_launch.py
Labels: fix

#356 fix: check for wte.weight along with embed_tokens.weight
  tuning/utils/merge_model_utils.py
Labels: fix
