Repository foundation-model-stack/fms-hf-tuning, pull requests merged in 2024-10, with the labels that each got.

#358 build(deps): unset hardcoded trl version to get latest updates
  pyproject.toml
Labels: build

#361 ci: run unit tests, fmt, image build on release branch
  .github/workflows/format.yml
  .github/workflows/image.yaml
  .github/workflows/test.yaml
Labels: ci

#363 chore: update code owners
  CODEOWNERS
Labels: chore

#364 fix: crash when output directory doesn't exist
  tuning/sft_trainer.py
Labels: fix

#348 refactor: move tokenizer_data_utils with the rest of utils, add further unit testing.
  scripts/run_inference.py
  tests/utils/test_embedding_resize.py
  tests/utils/test_tokenizer_data_utils.py
  tuning/data/__init__.py
  tuning/sft_trainer.py
  tuning/utils/tokenizer_data_utils.py
Labels: refactor

#355 build(deps): update transformers and accelerate deps
  pyproject.toml
Labels: build

#371 build(deps): Upgrade accelerate requirement to allow version 1.0.0
  fixtures/accelerate_fsdp_defaults.yaml
  pyproject.toml
  tests/build/dummy_job_config.json
  tests/build/test_utils.py
Labels: build

#370 build: Set triton environment variables
  build/Dockerfile
Labels: build

#375 build(deps): torch<2.5 due to FA2 error with new version
  pyproject.toml
Labels: build

#376 chore: merge set of changes for v2.1.0
  .github/workflows/format.yml
  .github/workflows/image.yaml
  .github/workflows/test.yaml
  CODEOWNERS
  build/Dockerfile
  fixtures/accelerate_fsdp_defaults.yaml
  pyproject.toml
  scripts/run_inference.py
  tests/build/dummy_job_config.json
  tests/build/test_utils.py
  tests/utils/test_embedding_resize.py
  tests/utils/test_tokenizer_data_utils.py
  tuning/data/__init__.py
  tuning/sft_trainer.py
  tuning/utils/tokenizer_data_utils.py
Labels: chore

#382 docs: Update Supported Models List in README
  README.md
Labels: docs
