Repository foundation-model-stack/fms-hf-tuning, pull requests merged in 2024-11, with the labels that each got.

#384 build(deps): set transformers below 4.46, waiting on fixes
  pyproject.toml
Labels: build

#386 chore(release): merge set of changes for v2.1.1
  README.md
  pyproject.toml
Labels: chore

#389 docs: Update supported models
  README.md
Labels: docs

#374 docs: Data Preprocessor ADR
  architecture_records/004-datapreprocessor.md
Labels: docs

#394 fix: bad name in generic tracker ADR
  architecture_records/003-generic-tracker-framework.md
Labels: fix
