Repository foundation-model-stack/fms-hf-tuning, pull requests merged in 2024-12, with the labels that each got.

#398 fix: Move test datasets to tests/artifacts/testdata instead of tests/data
  tests/acceleration/test_acceleration_framework.py
  tests/artifacts/testdata/__init__.py
  tests/artifacts/testdata/empty_data.json
  tests/artifacts/testdata/malformatted_data.json
  tests/artifacts/testdata/trainercontroller/__init__.py
  tests/artifacts/testdata/trainercontroller/epoch-level-eval-loss-patience.yaml
  tests/artifacts/testdata/trainercontroller/epoch-level-eval-loss.yaml
  tests/artifacts/testdata/trainercontroller/epoch-level-training-loss.yaml
  tests/artifacts/testdata/trainercontroller/exposed_metrics.yaml
  tests/artifacts/testdata/trainercontroller/incorrect_source_event_exposed_metrics.yaml
  tests/artifacts/testdata/trainercontroller/log_controller.yaml
  tests/artifacts/testdata/trainercontroller/loss_custom_metric.yaml
  tests/artifacts/testdata/trainercontroller/loss_custom_operation.yaml
  tests/artifacts/testdata/trainercontroller/loss_custom_operation_invalid_action.yaml
  tests/artifacts/testdata/trainercontroller/loss_invalid_metric.yaml
  tests/artifacts/testdata/trainercontroller/loss_invalid_operation.yaml
  tests/artifacts/testdata/trainercontroller/loss_invalid_operation_action.yaml
  tests/artifacts/testdata/trainercontroller/loss_invalid_trigger.yaml
  tests/artifacts/testdata/trainercontroller/loss_on_threshold.yaml
  tests/artifacts/testdata/trainercontroller/loss_on_threshold_with_trainer_state.yaml
  tests/artifacts/testdata/trainercontroller/loss_unavailable_metric.yaml
  tests/artifacts/testdata/trainercontroller/loss_with_invalid_type_rule.yaml
  tests/artifacts/testdata/trainercontroller/loss_with_malicious_input_rule.yaml
  tests/artifacts/testdata/trainercontroller/loss_with_malicious_os_rule.yaml
  tests/artifacts/testdata/trainercontroller/non-decreasing-training-loss.yaml
  tests/artifacts/testdata/trainercontroller/on-save.yaml
  tests/artifacts/testdata/trainercontroller/thresholded-training-loss.yaml
  tests/artifacts/testdata/twitter_complaints_input_output.json
  tests/artifacts/testdata/twitter_complaints_input_output.jsonl
  tests/artifacts/testdata/twitter_complaints_small.json
  tests/artifacts/testdata/twitter_complaints_small.jsonl
  tests/artifacts/testdata/twitter_complaints_tokenized_with_maykeye_tinyllama_v0.json
  tests/artifacts/testdata/twitter_complaints_tokenized_with_maykeye_tinyllama_v0.jsonl
  tests/build/test_launch_script.py
  tests/test_sft_trainer.py
  tests/trainercontroller/test_tuning_trainercontroller.py
  tests/utils/test_data_utils.py
  tests/utils/test_preprocessing_utils.py
  tests/utils/test_tokenizer_data_utils.py
Labels: fix

#406 fix: Limit trl version to <0.12
  pyproject.toml
Labels: fix

#407 chore: Release v2.2.0 after limiting TRL version
  pyproject.toml
Labels: chore

#401 feat: Add support to handle Parquet Dataset files via data config
  tests/artifacts/testdata/__init__.py
  tests/artifacts/testdata/parquet/twitter_complaints_input_output.parquet
  tests/artifacts/testdata/parquet/twitter_complaints_small.parquet
  tests/artifacts/testdata/parquet/twitter_complaints_tokenized_with_maykeye_tinyllama_v0.parquet
  tests/data/test_data_preprocessing_utils.py
  tuning/data/data_processors.py
  tuning/utils/utils.py
Labels: feat

#403 test: add arrow datasets and arrow unit tests
  tests/artifacts/testdata/__init__.py
  tests/artifacts/testdata/twitter_complaints_input_output.arrow
  tests/artifacts/testdata/twitter_complaints_small.arrow
  tests/artifacts/testdata/twitter_complaints_tokenized_with_maykeye_tinyllama_v0.arrow
  tests/data/test_data_preprocessing_utils.py
  tuning/utils/utils.py
Labels: test

#408 feat: Perform dataset mixing via sampling probabilities in data config
  tests/artifacts/predefined_data_configs/__init__.py
  tests/artifacts/predefined_data_configs/apply_custom_template.yaml
  tests/artifacts/predefined_data_configs/multiple_datasets_with_sampling.yaml
  tests/artifacts/predefined_data_configs/tokenize_and_apply_input_masking.yaml
  tests/data/test_data_preprocessing_utils.py
  tuning/data/data_config.py
  tuning/data/data_processors.py
Labels: feat

#409 feat: Expose additional data handlers as an argument in train
  tests/test_sft_trainer.py
  tuning/data/data_processors.py
  tuning/data/setup_dataprocessor.py
  tuning/sft_trainer.py
Labels: feat

#418 fix: update dataclass objects directly instead of creating new variables
  tuning/sft_trainer.py
Labels: fix

#415 feat: Add multi and single turn chat support
  .pylintrc
  tests/artifacts/testdata/__init__.py
  tests/artifacts/testdata/jsonl/multi_turn_chat.jsonl
  tests/artifacts/testdata/jsonl/single_turn_chat.jsonl
  tests/artifacts/testdata/tinyllama_tokenizer_special_tokens/added_tokens.json
  tests/artifacts/testdata/tinyllama_tokenizer_special_tokens/special_tokens_map.json
  tests/artifacts/testdata/tinyllama_tokenizer_special_tokens/tokenizer.json
  tests/artifacts/testdata/tinyllama_tokenizer_special_tokens/tokenizer.model
  tests/artifacts/testdata/tinyllama_tokenizer_special_tokens/tokenizer_config.json
  tests/data/test_data_preprocessing_utils.py
  tests/test_sft_trainer.py
  tuning/config/configs.py
  tuning/data/data_handlers.py
  tuning/data/data_preprocessing_utils.py
  tuning/data/setup_dataprocessor.py
  tuning/sft_trainer.py
Labels: feat

#425 feat: Integrate MLflow tracker
  .gitignore
  README.md
  build/Dockerfile
  docs/experiment-tracking.md
  pyproject.toml
  tests/test_sft_trainer.py
  tests/trackers/test_aim_tracker.py
  tests/trackers/test_mlflow_tracker.py
  tuning/config/tracker_configs.py
  tuning/sft_trainer.py
  tuning/trackers/aimstack_tracker.py
  tuning/trackers/mlflow_tracker.py
  tuning/trackers/tracker_factory.py
Labels: feat

#424 feat: Handle passing of multiple files, multiple folders, path with patterns, HF Dataset and combination
  tests/artifacts/predefined_data_configs/tokenize_and_apply_input_masking.yaml
  tests/artifacts/testdata/__init__.py
  tests/artifacts/testdata/datafolder/twitter_complaints_input_output_1.json
  tests/artifacts/testdata/datafolder/twitter_complaints_input_output_2.json
  tests/data/test_data_preprocessing_utils.py
  tests/test_sft_trainer.py
  tests/utils/test_config_utils.py
  tuning/data/data_config.py
  tuning/data/data_processors.py
  tuning/data/setup_dataprocessor.py
  tuning/utils/utils.py
Labels: feat

#423 docs: Add documentation for data preprocessor release
  README.md
  docs/advanced-data-preprocessing.md
Labels: docs

#429 fix: broken README.md link
  README.md
Labels: fix
