Repository foundation-model-stack/fms-hf-tuning, pull requests merged in 2025-02, with the labels that each got.

#438 feat: Add support for jinja based template rendering of the dataset
  docs/advanced-data-preprocessing.md
  tests/artifacts/predefined_data_configs/__init__.py
  tests/artifacts/predefined_data_configs/apply_custom_jinja_template.yaml
  tests/data/test_data_handlers.py
  tests/data/test_data_preprocessing_utils.py
  tuning/data/data_handlers.py
  tuning/utils/config_utils.py
Labels: feat

#454 fix: bug in aim tracker where the server based tracking was not picked
  tuning/trackers/aimstack_tracker.py
Labels: fix

#444 fix: remove duplicate main_process_port entry
  README.md
Labels: fix

#455 fix: space missing from data_formatter_template causing mismatch with response_template
  README.md
Labels: fix

#456 fix: Using Sandboxed Environment in handler rendering Jinja template
  tests/data/test_data_handlers.py
  tuning/data/data_handlers.py
Labels: fix

#461 docs: Add documentation on how to do EPT runs with our library.
  README.md
  docs/ept.md
Labels: docs

#462 feat: Packing for pretokenised datasets
  tests/data/test_data_preprocessing_utils.py
  tuning/data/setup_dataprocessor.py
Labels: feat

#465 fix:Retrieval of tokenizer_kwargs in data handler tokenize_and_apply_input_masking
  tests/data/test_data_preprocessing.py
  tuning/data/data_handlers.py
Labels: fix

#466 feat: Add support for renaming and retaining columns in data preprocessor
  docs/advanced-data-preprocessing.md
  docs/ept.md
  tests/artifacts/predefined_data_configs/__init__.py
  tests/artifacts/predefined_data_configs/rename_retain_columns.yaml
  tests/data/test_data_preprocessing.py
  tests/test_sft_trainer.py
  tuning/data/data_config.py
  tuning/data/data_processors.py
Labels: feat

#448 chore(deps): upgrade trl and transformers
  pyproject.toml
  tests/build/test_launch_script.py
  tests/data/test_data_preprocessing.py
  tests/test_sft_trainer.py
  tuning/data/setup_dataprocessor.py
Labels: chore

#467 feat: adding eos token to be made a flag so we don't force it on every handler
  docs/advanced-data-preprocessing.md
  tests/artifacts/predefined_data_configs/apply_custom_jinja_template.yaml
  tests/artifacts/predefined_data_configs/apply_custom_template.yaml
  tests/artifacts/predefined_data_configs/tokenize_and_apply_input_masking.yaml
  tests/data/test_data_preprocessing.py
  tuning/data/data_handlers.py
Labels: feat
