Repository foundation-model-stack/fms-hf-tuning, pull requests merged in 2025-04, with the labels that each got.

#514 feat: new interface for fast_moe (non breaking)
  README.md
  tests/test_sft_trainer.py
  tuning/config/acceleration_configs/fast_moe.py
  tuning/config/acceleration_configs/utils.py
Labels: feat

#517 fix: additional special tokens being replaced
  scripts/offline_data_processing.py
  tests/utils/test_embedding_resize.py
  tuning/utils/tokenizer_data_utils.py
Labels: fix

#518 fix: downgrade transformers due to breaking change in loading from checkpoint.
  pyproject.toml
Labels: fix

#493 fix: (data pre-process) un-escape templates and strings passed on cli correctly
  tuning/config/configs.py
Labels: fix

#475 refactor: refactor set special tokens function and add unit tests.
  scripts/offline_data_processing.py
  tests/utils/test_tokenizer_data_utils.py
  tuning/sft_trainer.py
  tuning/utils/tokenizer_data_utils.py
Labels: refactor

#519 feat: Add OI style data handler for chat template usecase
  tests/artifacts/predefined_data_configs/__init__.py
  tests/artifacts/predefined_data_configs/mt_data_granite_3_1B_tokenize_and_mask_handler.yaml
  tests/test_sft_trainer.py
  tuning/data/data_handlers.py
  tuning/data/data_preprocessing_utils.py
Labels: feat

#516 fix: set use_cache=false while model loading to prevent graph break
  tuning/sft_trainer.py
Labels: fix

#522 docs: update the `--data_config` flag to `--data_config_path`
  docs/advanced-data-preprocessing.md
  docs/ept.md
Labels: docs

#521 feat: expose conversation_column in data_args
  README.md
  tests/artifacts/testdata/__init__.py
  tests/artifacts/testdata/jsonl/multi_turn_chat_conversations.jsonl
  tests/test_sft_trainer.py
  tuning/config/configs.py
  tuning/data/setup_dataprocessor.py
Labels: feat

#520 feat: [experimental] enable sum loss trainer
  tests/test_sft_trainer.py
  tuning/config/configs.py
  tuning/sft_trainer.py
  tuning/trainers/sum_loss_sft_trainer.py
Labels: feat

#525 fix: add init file and header
  tuning/trainers/__init__.py
  tuning/trainers/sum_loss_sft_trainer.py
Labels: fix

#526 fix: multipack and streaming are incompatible
  README.md
  docs/advanced-data-preprocessing.md
  tests/data/test_data_preprocessing.py
  tuning/config/acceleration_configs/attention_and_distributed_packing.py
  tuning/data/setup_dataprocessor.py
  tuning/sft_trainer.py
Labels: fix

#512 build(image): add fast_moe into fms-hf-tuning image
  build/Dockerfile
Labels: build

#528 fix: change the default model_name_or_path from "facebook/opt-125m" to None
  tuning/config/configs.py
  tuning/sft_trainer.py
Labels: fix

#527 build: Upgrade TRL version from 0.14 to 0.16
  README.md
  examples/prompt_tuning_twitter_complaints/README.md
  pyproject.toml
  tests/artifacts/predefined_data_configs/duplicate_columns.yaml
  tests/artifacts/predefined_data_configs/skip_large_text_data_handler_template.yaml
  tests/artifacts/predefined_data_configs/tokenize_using_handler_and_train.yaml
  tests/artifacts/testdata/arrow/twitter_complaints_tokenized_with_maykeye_tinyllama_v0.arrow
  tests/artifacts/testdata/json/twitter_complaints_tokenized_with_maykeye_tinyllama_v0.json
  tests/artifacts/testdata/json/twitter_complaints_tokenized_with_maykeye_tinyllama_v0_only_input_ids.json
  tests/artifacts/testdata/jsonl/twitter_complaints_tokenized_with_maykeye_tinyllama_v0.jsonl
  tests/artifacts/testdata/parquet/twitter_complaints_tokenized_with_maykeye_tinyllama_v0.parquet
  tests/build/test_launch_script.py
  tests/data/test_data_preprocessing.py
  tests/test_sft_trainer.py
  tuning/data/data_preprocessing_utils.py
  tuning/sft_trainer.py
Labels: build

#524 fix: Update CODEOWNERS
  CODEOWNERS
Labels: fix

#501 chore: Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: chore

#531 fix:Remove use_cache and update ReadMe.
  README.md
  tuning/sft_trainer.py
Labels: fix

#530 feat: Enable LoRA saving only for non MoE linear layers training with kernels.
  .pylintrc
  README.md
  build/accelerate_launch.py
  tests/acceleration/test_acceleration_framework.py
  tests/test_sft_trainer.py
  tuning/config/acceleration_configs/fast_moe.py
  tuning/sft_trainer.py
Labels: feat

#538 ci: use --no-build-isolation flag for mamba
  build/Dockerfile
Labels: ci

#537 chore(deps): upgrade trl
  docs/offline-data-preprocessing.md
  pyproject.toml
Labels: chore

#539 fix: revert "chore(deps): upgrade trl"
  docs/offline-data-preprocessing.md
  pyproject.toml
Labels: fix

#536 fix: yaml parsing converts floats like 1.0 into integer 1 causing assertion failure
  tuning/data/data_config.py
Labels: fix

#540 build(deps): upgrade trl
  docs/offline-data-preprocessing.md
  pyproject.toml
  tests/data/test_data_preprocessing.py
  tuning/data/data_preprocessing_utils.py
Labels: build

#534 feat: allow specifying the chat template as base64 to avoid weird escaping and templating issues
  tests/artifacts/predefined_data_configs/__init__.py
  tests/artifacts/predefined_data_configs/granite_3_1b_chat_template.txt
  tests/artifacts/predefined_data_configs/granite_3_1b_invalid_base64_data_handler.yaml
  tests/artifacts/predefined_data_configs/granite_3_1b_valid_base64_data_handler.yaml
  tests/test_sft_trainer.py
  tuning/data/data_config.py
Labels: feat

#542 ci: Install dnf-plugins-core in cuda-base stage
  build/Dockerfile
Labels: ci

#543 chore(release): merge set of changes for v2.8.1
  build/Dockerfile
  tests/artifacts/predefined_data_configs/__init__.py
  tests/artifacts/predefined_data_configs/granite_3_1b_chat_template.txt
  tests/artifacts/predefined_data_configs/granite_3_1b_invalid_base64_data_handler.yaml
  tests/artifacts/predefined_data_configs/granite_3_1b_valid_base64_data_handler.yaml
  tests/test_sft_trainer.py
  tuning/data/data_config.py
Labels: chore

#544 fix: incorrect check on fast moe activation
  tuning/sft_trainer.py
Labels: fix

#546 docs: add addt vision model support
  README.md
Labels: docs

#545 fix: fastmoe lora `all-linear` excluding `router`
  tuning/sft_trainer.py
Labels: fix

#547 chore(release): merge set of changes for v2.8.2
  README.md
  tuning/sft_trainer.py
Labels: chore
