Repository foundation-model-stack/fms-hf-tuning, pull requests merged in 2025-01, with the labels that each got.

#431 feat: Allow hf dataset id to be passed via training_data_path
  README.md
  tests/test_sft_trainer.py
  tuning/data/data_handlers.py
  tuning/data/data_processors.py
Labels: feat

#430 feat: allow for padding free plugin to be used without response template
  .github/workflows/image.yaml
  tests/data/test_data_preprocessing_utils.py
  tuning/config/acceleration_configs/attention_and_distributed_packing.py
  tuning/data/data_preprocessing_utils.py
  tuning/data/setup_dataprocessor.py
  tuning/sft_trainer.py
Labels: feat

#434 fix: function name from `requires_agumentation` to `requires_augmentation`
  tests/acceleration/test_acceleration_framework.py
  tuning/sft_trainer.py
Labels: fix

#436 fix: Add pad_token to special_tokens_dict when pad_token == eos_token
  tuning/sft_trainer.py
Labels: fix

#441 docs: update granite3 model support
  README.md
Labels: docs

#443 docs: EOS token support
  README.md
Labels: docs

#422 feat: add scanner tracker
  build/Dockerfile
  pyproject.toml
  tests/build/test_launch_script.py
  tests/test_sft_trainer.py
  tests/trackers/test_hf_resource_scanner_tracker.py
  tuning/config/tracker_configs.py
  tuning/sft_trainer.py
  tuning/trackers/hf_resource_scanner_tracker.py
  tuning/trackers/tracker_factory.py
Labels: feat

#447 docs: add note to note that file extension is required in training data path
  README.md
Labels: docs

#445 feat: updates documentation with chat template guide flowchart
  README.md
  docs/images/chat_template_guide.jpg
Labels: feat

#453 chore: Merge in changes for v2.5.0 release
  .github/workflows/build-and-publish.yaml
  .github/workflows/coverage.yaml
  .github/workflows/format.yml
  .github/workflows/test.yaml
  README.md
  build/Dockerfile
  docs/images/chat_template_guide.jpg
  pyproject.toml
  tests/build/test_launch_script.py
  tests/test_sft_trainer.py
  tests/trackers/test_hf_resource_scanner_tracker.py
  tuning/config/tracker_configs.py
  tuning/sft_trainer.py
  tuning/trackers/hf_resource_scanner_tracker.py
  tuning/trackers/tracker_factory.py
Labels: chore

#446 fix: Hardcode Legacy behavior to True to resolve warning.
  tuning/sft_trainer.py
Labels: fix
