Repository foundation-model-stack/fms-hf-tuning, pull requests merged in 2025-06, with the labels that each got.

#513 feat: Add ALoRA support
  README.md
  pyproject.toml
  scripts/run_inference.py
  tests/test_sft_trainer.py
  tuning/data/setup_dataprocessor.py
  tuning/sft_trainer.py
  tuning/utils/config_utils.py
  tuning/utils/import_utils.py
Labels: feat

#557 fix: decouple and update concatenate_dataset functionality from load_dataset
  tests/data/test_data_preprocessing.py
  tuning/data/data_processors.py
  tuning/data/utils.py
Labels: fix

#561 chore: Upgrade transformers, torch, and accelerate version
  pyproject.toml
Labels: chore

#560 feat: add train_test_split functionality via dataconfig
  docs/advanced-data-preprocessing.md
  tests/artifacts/predefined_data_configs/__init__.py
  tests/artifacts/predefined_data_configs/multiple_datasets_with_sampling_and_split.yaml
  tests/data/test_data_preprocessing.py
  tests/test_sft_trainer.py
  tuning/config/configs.py
  tuning/data/data_config.py
  tuning/data/data_handlers.py
  tuning/data/data_processors.py
  tuning/data/setup_dataprocessor.py
Labels: feat

#570 fix: docs and minor code
  docs/advanced-data-preprocessing.md
  docs/offline-data-preprocessing.md
  tuning/data/data_config.py
Labels: fix

#573 fix: Add ENABLE_MLFLOW build argument to Dockerfile to control MLflow integration
  build/Dockerfile
Labels: fix
