Repository foundation-model-stack/fms-hf-tuning, pull requests merged in 2025-03, with the labels that each got.

#437 feat: Enable streaming in data preprocessor
  docs/advanced-data-preprocessing.md
  docs/ept.md
  tests/artifacts/predefined_data_configs/__init__.py
  tests/artifacts/predefined_data_configs/apply_custom_template_streaming.yaml
  tests/artifacts/predefined_data_configs/pretokenized_json_data_streaming.yaml
  tests/artifacts/predefined_data_configs/tokenize_and_apply_input_masking_streaming.yaml
  tests/data/test_data_handlers.py
  tests/data/test_data_preprocessing.py
  tests/test_sft_trainer.py
  tuning/data/data_config.py
  tuning/data/data_processors.py
  tuning/data/setup_dataprocessor.py
  tuning/utils/utils.py
Labels: feat

#473 feat: Support for add special tokens via cli args
  README.md
  tests/test_sft_trainer.py
  tuning/config/configs.py
  tuning/sft_trainer.py
Labels: feat

#474 feat: add support for chat template from data config
  docs/advanced-data-preprocessing.md
  tests/artifacts/predefined_data_configs/__init__.py
  tests/artifacts/predefined_data_configs/multi_turn_data_with_chat_template.yaml
  tests/test_sft_trainer.py
  tuning/data/data_config.py
  tuning/data/setup_dataprocessor.py
  tuning/sft_trainer.py
Labels: feat

#487 feat: Add tokenizer data handler.
  docs/advanced-data-preprocessing.md
  tests/artifacts/predefined_data_configs/__init__.py
  tests/artifacts/predefined_data_configs/tokenize_using_handler_and_train.yaml
  tests/data/test_data_handlers.py
  tests/test_sft_trainer.py
  tuning/data/data_handlers.py
Labels: feat

#458 fix: use main_process_first instead of broadcast_object_list
  tuning/data/data_processors.py
Labels: fix

#490 fix: data handler to string conversion bug
  tuning/data/data_handlers.py
Labels: fix

#491 feat: add sum op for trainer controller
  tuning/utils/evaluator.py
Labels: feat

#486 feat: support moe hf chkpt
  README.md
  tests/test_sft_trainer.py
  tuning/config/acceleration_configs/__init__.py
  tuning/config/acceleration_configs/callbacks.py
  tuning/config/acceleration_configs/fast_moe.py
  tuning/sft_trainer.py
Labels: feat

#419 fix: Remove deprecated push_to_hub_token to resolve warning
  tuning/sft_trainer.py
Labels: fix

#495 feat: Add tools and documents usage in chat template
  tests/artifacts/predefined_data_configs/__init__.py
  tests/artifacts/predefined_data_configs/multi_turn_data_with_chat_template.yaml
  tests/artifacts/predefined_data_configs/multi_turn_data_with_chat_template_granite_3_1B.yaml
  tests/artifacts/testdata/__init__.py
  tests/artifacts/testdata/jsonl/multi_turn_chat_granite_instruct.jsonl
  tests/test_sft_trainer.py
  tuning/data/data_handlers.py
Labels: feat

#459 test:Addition of data preprocessing script, decoupling data preprocessor from the tuning
  docs/advanced-data-preprocessing.md
  scripts/offline_data_processing.py
  tests/data/test_data_preprocessing.py
Labels: test

#500 fix: bug which caused test case failures after PR merge
  tests/data/test_data_preprocessing.py
Labels: fix

#504 chore(release): merge set of changes for v2.7.0
  .github/actions/free-up-disk-space/action.yml
  .github/workflows/image.yaml
  README.md
  build/Dockerfile
  docs/advanced-data-preprocessing.md
  docs/ept.md
  pyproject.toml
  scripts/offline_data_processing.py
  tests/artifacts/predefined_data_configs/__init__.py
  tests/artifacts/predefined_data_configs/apply_custom_template_streaming.yaml
  tests/artifacts/predefined_data_configs/multi_turn_data_with_chat_template.yaml
  tests/artifacts/predefined_data_configs/multi_turn_data_with_chat_template_granite_3_1B.yaml
  tests/artifacts/predefined_data_configs/pretokenized_json_data_streaming.yaml
  tests/artifacts/predefined_data_configs/skip_large_text_data_handler_template.yaml
  tests/artifacts/predefined_data_configs/tokenize_and_apply_input_masking_streaming.yaml
  tests/artifacts/predefined_data_configs/tokenize_using_handler_and_train.yaml
  tests/artifacts/testdata/__init__.py
  tests/artifacts/testdata/jsonl/multi_turn_chat_granite_instruct.jsonl
  tests/data/test_data_handlers.py
  tests/data/test_data_preprocessing.py
  tests/test_sft_trainer.py
  tests/utils/test_evaluator.py
  tuning/config/acceleration_configs/__init__.py
  tuning/config/acceleration_configs/callbacks.py
  tuning/config/acceleration_configs/fast_moe.py
  tuning/config/configs.py
  tuning/data/data_config.py
  tuning/data/data_handlers.py
  tuning/data/data_processors.py
  tuning/data/setup_dataprocessor.py
  tuning/sft_trainer.py
  tuning/utils/evaluator.py
  tuning/utils/utils.py
Labels: chore

#506 fix: Use main process first instead of local_main_process_first
  tuning/data/data_processors.py
Labels: fix

#503 fix: save model dir hf moe checkpoint
  tests/test_sft_trainer.py
  tuning/config/acceleration_configs/fast_moe.py
  tuning/sft_trainer.py
Labels: fix

#507 build(deps): install mamba_ssm from package instead of github
  pyproject.toml
Labels: build

#508 build(deps): install mamba_ssm from package instead of github
  pyproject.toml
Labels: build

#502 docs: Offline Data Preprocessing documentation
  README.md
  docs/advanced-data-preprocessing.md
  docs/offline-data-preprocessing.md
Labels: docs

#510 docs: add flash debug steps to docs
  README.md
Labels: docs
